name: test-ci

on:
  push:
    branches:
      - master

jobs:
  # 任务jobID
  build:
    runs-on: ubuntu-latest
    steps:
      # 使用别人的action:
      # checkout@v3:拉代码
      # setup-node@v3:设置特定nodejs版本
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: npm install
      - name: Build
        run: npm run docs:build
      - name: copy demos and other files
        run: |
          cd docs/.vuepress/dist
          cp -r ../../../.github ./
          cp -r ../../../CNAME ./
          cp -r ../../../demos ./
          cd -
          pwd
      - name: deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run gh-deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ericyangxd.github.io

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.ACCESS_TOKEN }}
      #     publish_dir: ./dist
      # - name: Sync To Gitee & Github
      #   run: |

      #     git push -f git@github.com:EricYangXD/ericyangxd.github.io.git master:gh-pages
      #     git push -f git@gitee.com:EricYangXD/my-vuepress-blog.git master
      #     git push -f git@gitee.com:EricYangXD/my-vuepress-blog.git master:gh-pages
      - uses: Yikun/hub-mirror-action@master
        with:
          src: "github/EricYangXD"
          dst: "gitee/EricYangXD"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          mappings: "ericyangxd.github.io=>my-vuepress-blog"
          static_list: "ericyangxd.github.io"
          force_update: true
          debug: true
      - name: Done
        run: |
          echo "Complete Successfully!"
      # 命名这个任务为发布Deploy
      - name: Deploy
        # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个拷贝操作
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.USER_HOST_129_146_238_23 }}
          user: ${{ secrets.USER_NAME_129_146_238_23 }}
          pass: ${{ secrets.USER_PASS_129_146_238_23 }}
          connect_timeout: 30s
          local: "./dist/*"
          remote: /home/blog/dist
