name: test-ci

on:
  push:
    branches:
      - master

jobs:
  # 任务jobID
  build:
    runs-on: ubuntu-latest
    steps:
      # 使用别人的action:
      # checkout@v3:拉代码
      # setup-node@v3:设置特定nodejs版本
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      # 设置nodejs版本
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # 安装依赖
      - name: Install
        run: npm install

      # 更新browserslist
      - name: Update-browserslist
        run: npx browserslist@latest --update-db

      # 构建打包
      - name: Build
        run: npm run docs:build

      # 把一些其他文件也拷贝到dist文件夹下
      # cp -r ../../../.github ./
      - name: Copy demos and other files to dist
        run: |
          pwd
          cd /home/runner/work/ericyangxd.github.io/ericyangxd.github.io/dist
          cp -r ../CNAME ./
          cp -r ../demos ./
          cd -
          pwd

      # 使用gh-pages发布
      # - name: deploy with gh-pages
      #   run: |
      #     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #     npm run gh-deploy -- -u "github-actions-bot <support+actions@github.com>"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     GITHUB_REPOSITORY: ericyangxd.github.io

      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          email: username@domain.tld
          build_dir: dist # optional
          branch: master # optional
          cname: ericyangxd.top # optional
          jekyll: no # optional
          commit_message: "deploy" # optional

      # 把代码同步到Gitee
      - uses: Yikun/hub-mirror-action@master
        with:
          src: "github/EricYangXD"
          dst: "gitee/EricYangXD"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          mappings: "ericyangxd.github.io=>my-vuepress-blog"
          static_list: "ericyangxd.github.io"
          force_update: true
          debug: true

      # 发布到云服务器上
      - name: Deploy to server
        # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个拷贝操作
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.USER_HOST_129_146_238_23 }}
          user: ${{ secrets.USER_NAME_129_146_238_23 }}
          pass: ${{ secrets.USER_PASS_129_146_238_23 }}
          connect_timeout: 30s
          local: "/home/runner/work/ericyangxd.github.io/ericyangxd.github.io/dist/*"
          remote: /home/blog/dist/

      # 全流程结束
      - name: Done
        run: |
          echo "Complete Successfully!"
