name: syncToGitee
on:
    push:
        branches:
            - gh-pages
jobs:
    repo-sync:
        runs-on: ubuntu-latest
        steps:
            - name: Mirror the Github organization repos to Gitee.
              uses: Yikun/hub-mirror-action@master
              with:
                  src: "github/EricYangXD"
                  dst: "gitee/EricYangXD"
                  dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
                  dst_token: ${{ secrets.GITEE_TOKEN_FOR_GITHUB }}
                  static_list: "my-vuepress-blog"
                  force_update: true
                  debug: true
